Add tty column -  To fix the wrong directory for the commands such as "exec bash" and "source ~/.bashrc" -  To keep tabs which "tty" the commands has been executed.
  The example function which uses cd, where the previous directory is wrong seems to have been fixed.

  mdd () {
    mkdir -p -- "$@" && cd "${@:-1}"
  }

  Even is you do something like.

  mdd /tmp/foobar; exec bash

  and check the commands in the same tty or another tty the directory seems to have been fixed also.

Edit the file README.
-  Add the tty column on the headers.
-  Add more option on howto enable ''set -o history''
-  Add ''How does it work'' section and explain some brief info.
-  Add ''tty'' column on the sqlite3 example commands.
-  Add choice 4 on the "If you hate eval don't use it section"

Edit the RELEASENOTE
-  Change 3.2.2 to 3.3.3
-  Add instruction howto create a new tty column.

Edit the sdb script.
-  Edit the lists of option in the Options of the sdb script.
-  Remove the B.
-  Add
    if [[ "$(set -o | awk '$1 == "history" {print $2}')" = off ]]; then
      set -o history
    fi
   To the configuration instruction on the sdb script.

-  Change the checking of bash version to a function so return can work.
   * __sdb_check_bash_version

-  Remove/change the ''-o|--off-pager'' to ''-o, --other-users'' in the help function
   * The --off-pager is slow and maybe unecessary, if you want the pager to go away then pipe the command into cat.
   * e.g. ''sdb -vcam+ | cat'' and enjoy viewing the long commands that is not the same line...
   * The --other-users is needed to view other users (if any) which is using the database/table.
   * Since the default now is just to show the current $USER or $LOGNAME.

-  Add the 6th column which is the tty column to the ''ORDER OF COLUMNS''.
-  Add a new function to check for the value of the previous cwd in the directories table.
   * __sdb_recent_pwd
-  When opening a new terminal or when the problematic commands are executed the current pwd is inserted in the table.
   * since there is a new __sdb_recent_pwd function we check first if the rececnt pwd is not the same as the current pwd.
   * then we insert to the directories table to avoid duplicate entries as much as possible.
   * ''if [[ -f $__sdb_file && $(__sdb_recent_pwd) != $__sdb_pwd ]]; then''
-  Add new variables to the __sdb_prompt function.
   * pts
   * previous_pts
   * status_command
-  Add new array to the __sdb_prompt function.
   * limit

-  The __sdb_prompt can keep tabs on which/where directories the commands has been executed.
   * Add a test if the previous pwd is not the same as the current pwd before inserting the current pwd.
   * ''if [[ $(__sdb_recent_pwd) != $__sdb_pwd ]]; then''

-  Change the parsion of ''history 2'' output
   * from

     while builtin read -r history2_output
       IFS=$'\n' builtin read -rd '' history1_output; do
       builtin return
     done

   * to

    { builtin read -r history2_output; IFS=$'\n' builtin read -rd '' history1_output; } < <(builtin history 2)

    * Since the former does not capture properly commands sucn as heredocs because of the return in the loop.
    * It should be like

      while builtin read -r history2_output
        IFS=$'\n' builtin read -rd '' history1_output; do
        :
      done

    * But why loop when you can group! :-)

-  Add  a test if the there is an exit status for the commands that begins with ''exec'' and ''source''
   * If there is no exit status or if the file ''/tmp/${__sdb_logname_}_sdb_last_status'' is empty then
   * Parse ''history 2'' since commands such as
     ''exec {fd}< <(env); while read -ru"$fd"; do :; done; declare -p fd''
     ''exec foobard''
   * Has an exit status, the former is zero and the latter is 127, except if you have an executable named ''foobard''.
   * Those commands will be parsed/seen in ''history 2'' also, so we avoid duplicate entries in the histor table.
-  Delete the file ''/tmp/${__sdb_logname_}_sdb_last_status'' if it is not empty.
-  If the command begin with ''exec'' or ''source'' then print the exit status to the ''/tmp/${__sdb_logname_}_sdb_last_status''

-  Add new variable to the sdb function.
   * Others
   * temporary_dir
   * temporary_file
   * tty0
   * tty1
   * tty2
-  Add new arrays in the sdb function.
   * hrt
   * sqlcommands
   * sql_commands{0..14}
-  Remove the extraneous under scores in the local variables

-  Fix the ignored pattern in the case statement. from the getops from scratch by D.J. Mills.
   * from
      ''-[!-]?*)''
   * to
     ''-[!-0-9]?*)''
   * The former ignores EVERYTHING that does not starts with a dash.
   * The latter includes digit/numeric strings that starts with a dash.
   * Remove the previous code
     ''[[ $1 = -[[:digit:]]* ]] && options+=("$1") && shift''

-  Remove the use of FD as a tempfile and reverted to the use of mktemp and trap for removing/deleting tempfiles.
   * Gui text editors seems to spit out some error when editing the output of the query.
   * Since the path to the tempfile is like /dev/fd/[[:digit:]]

-  Remove the ''cmd FROM history WHERE 1'' from the first_sqlite_commands variable.
   * Add it to the new created arrays.
   * To have an nice format when the -v|--versbose is specified.

-  The new sql_command{0..15} arrays are used in order to have a nice HUMAN READABLE format/output when the -v|--verbose is specified.
   * The epoch is converted in to a human readable format.
   * GNU date format "+%F %T" which is the same as what the DATE/TIME column is showing in the query.
   * The previous shows the raw epoch date but me personnaly cannot convert epoch into a human readable format by just looking at it :).
-  Remove the use of printf when feeding the sql commands that are saved in the sql_commands arrays.
   * It is slow when since it invoke printf even if it is a builtin.
   * The herestring ''<<<'' is more faster.

CAVEATS

-  When using fifos

  * In tty1
    ''mkfiro my /tmp/myfifo''
    ''echo foo > /tmp/myfifo''

  * in tty2
    ''read -r var < /tmp/myfifo''

  * Error pops up in tty1
    Error: database is locked

Not sure if it is just a missing compiled option or it is just like that... :(